
package dialog;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import action.UserAction;
import data.User;

/**
 * 用户配置窗体
 * @author  spacelis
 */
public class Configuration extends javax.swing.JDialog {
	private User user = null;
	private List<User> userlist = new ArrayList<User>();
	DefaultListModel lm = new DefaultListModel();

	/** Creates new form Configuration */
	public Configuration(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
	}

	/**
	 * 构造方法，传入当前用户设置
	 * @param user当前用户设置
	 */
	public Configuration(User user) {
		this(new javax.swing.JFrame(), true);//调用原始构造方法
		try {
			UserAction.regin(userlist);
		} catch (IOException e1) {
			JOptionPane.showConfirmDialog(null, "读取用户信息失败", "错误",
					JOptionPane.OK_OPTION);
			e1.printStackTrace();
		}
		if ("".equals(user.getUsername())) {
			if (userlist.size() != 0) {
				this.user = userlist.get(0);
			} else {
				this.user = user;
			}
		} else {
			userlist.remove(userlist.indexOf(user));
			userlist.add(0, user);
			this.user = user;
		}

		if (userlist.size() != 0) {

			for (Iterator<User> it = userlist.iterator(); it.hasNext();) {
				lm.addElement(it.next().getUsername());
			}
		}

		initComponents();
		userList.setModel(lm);
		//		usernameTextField.setText("thz1987");
		//		passwordTextField.setText("leaddowuhan");
		usernameTextField.setText(user.getUsername());
		passwordTextField.setText(user.getPassword());
		for (int i = 0; i < smtpComboBox.getItemCount(); i++) {
			if (user.getSmtpServer().equals(smtpComboBox.getItemAt(i))) {
				smtpComboBox.setSelectedIndex(i);
				break;
			}
		}
		for (int i = 0; i < popComboBox.getItemCount(); i++) {
			if (user.getPopServer().equals(popComboBox.getItemAt(i))) {
				popComboBox.setSelectedIndex(i);
				break;
			}
		}

		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent e) {
				dispose();
			}
		});

		setLocation(320, 220);
		setVisible(true);
	}

	public User getUser() {
		return user;
	}

	/** 初始化窗口组件
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		label1 = new java.awt.Label();
		label2 = new java.awt.Label();
		label3 = new java.awt.Label();
		label4 = new java.awt.Label();
		smtpComboBox = new javax.swing.JComboBox();
		popComboBox = new javax.swing.JComboBox();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		usernameTextField = new javax.swing.JTextField();
		passwordTextField = new javax.swing.JPasswordField();
		jScrollPane1 = new javax.swing.JScrollPane();
		userList = new javax.swing.JList();
		jButton4 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();

		setTitle("\u7528\u6237\u8bbe\u7f6e");
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		label1.setText("\u7528\u6237\u540d");

		label2.setText("\u5bc6\u7801");

		label3.setText("SMTP\u670d\u52a1\u5668");

		label4.setText("POP3\u670d\u52a1\u5668");

		smtpComboBox.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "smtp.qq.com", "smtp.sohu.com", "smtp.126.com",
						"smtp.163.com", "smtp.gmail.com" }));
		smtpComboBox.setEditable(true);

		popComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"pop.qq.com", "pop.sohu.com", "pop.126.com", "pop.163.com",
				"pop.gmail.com" }));
		popComboBox.setEditable(true);

		jButton1.setText("\u786e\u5b9a");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u53d6\u6d88");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		userList.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				userListMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(userList);

		jButton4.setText("-");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton3.setText("+");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								org.jdesktop.layout.GroupLayout.TRAILING,
								layout
										.createSequentialGroup()
										.add(23, 23, 23)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING,
																false)
														.add(
																jScrollPane1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																117,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				jButton4)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.add(
																				jButton3)))
										.add(13, 13, 13)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.LEADING)
																		.add(
																				layout
																						.createSequentialGroup()
																						.add(
																								layout
																										.createParallelGroup(
																												org.jdesktop.layout.GroupLayout.LEADING)
																										.add(
																												label3,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																										.add(
																												label4,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																						.add(
																								32,
																								32,
																								32)
																						.add(
																								layout
																										.createParallelGroup(
																												org.jdesktop.layout.GroupLayout.LEADING)
																										.add(
																												popComboBox,
																												0,
																												147,
																												Short.MAX_VALUE)
																										.add(
																												smtpComboBox,
																												0,
																												147,
																												Short.MAX_VALUE)))
																		.add(
																				org.jdesktop.layout.GroupLayout.TRAILING,
																				layout
																						.createSequentialGroup()
																						.add(
																								layout
																										.createParallelGroup(
																												org.jdesktop.layout.GroupLayout.LEADING)
																										.add(
																												label1,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												52,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																										.add(
																												label2,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												62,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																						.addPreferredGap(
																								org.jdesktop.layout.LayoutStyle.RELATED,
																								18,
																								Short.MAX_VALUE)
																						.add(
																								layout
																										.createParallelGroup(
																												org.jdesktop.layout.GroupLayout.LEADING,
																												false)
																										.add(
																												passwordTextField)
																										.add(
																												usernameTextField,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												171,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				131,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.add(
																				jButton1)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jButton2)))
										.add(56, 56, 56)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				35,
																				35,
																				35)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.TRAILING)
																						.add(
																								label1,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																						.add(
																								usernameTextField,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								label2,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																						.add(
																								passwordTextField,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																		.add(
																				40,
																				40,
																				40)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.TRAILING)
																						.add(
																								label3,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																						.add(
																								smtpComboBox,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								label4,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																						.add(
																								popComboBox,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.BASELINE)
																						.add(
																								jButton2)
																						.add(
																								jButton1)))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				27,
																				27,
																				27)
																		.add(
																				jScrollPane1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				183,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.BASELINE)
																						.add(
																								jButton4)
																						.add(
																								jButton3))))
										.addContainerGap(29, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents
	
	/**
	 * 添加用户
	 */
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		usernameTextField.setText("");
		passwordTextField.setText("");
	}
	
	/**
	 * List的鼠标事件
	 * @param evt
	 */
	private void userListMouseClicked(java.awt.event.MouseEvent evt) {
		user = userlist.get(userList.getSelectedIndex());
		usernameTextField.setText(user.getUsername());
		passwordTextField.setText(user.getPassword());
		for (int i = 0; i < smtpComboBox.getItemCount(); i++) {
			if (user.getSmtpServer().equals(smtpComboBox.getItemAt(i))) {
				smtpComboBox.setSelectedIndex(i);
				break;
			}
		}
		for (int i = 0; i < popComboBox.getItemCount(); i++) {
			if (user.getPopServer().equals(popComboBox.getItemAt(i))) {
				popComboBox.setSelectedIndex(i);
				break;
			}
		}
	}

	/**
	 * 删除按钮
	 * @param evt
	 */
	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		if (JOptionPane.OK_OPTION == JOptionPane.showConfirmDialog(null,
				"确实要删除此记录？", "提示	", JOptionPane.OK_CANCEL_OPTION)) {
			userlist.remove(userList.getSelectedIndex());
			lm.remove(userList.getSelectedIndex());
			User u = userlist.get(0);
			usernameTextField.setText(u.getUsername());
			passwordTextField.setText(u.getPassword());
			for (int i = 0; i < smtpComboBox.getItemCount(); i++) {
				if (u.getSmtpServer().equals(smtpComboBox.getItemAt(i))) {
					smtpComboBox.setSelectedIndex(i);
					break;
				}
			}
			for (int i = 0; i < popComboBox.getItemCount(); i++) {
				if (u.getPopServer().equals(popComboBox.getItemAt(i))) {
					popComboBox.setSelectedIndex(i);
					break;
				}
			}
		}
	}

	/**
	 * 取消按钮
	 */
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
	}

	/**
	 * 确定按钮
	 * @param evt
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

		if ("".equals(usernameTextField.getText())) {
			JOptionPane.showConfirmDialog(null, "请填写用户名", "错误",
					JOptionPane.YES_NO_OPTION);
			return;
		} else if ("".equals(passwordTextField.getText())) {
			JOptionPane.showConfirmDialog(null, "请填写密码", "错误",
					JOptionPane.YES_NO_OPTION);
			return;
		} else if ("".equals(smtpComboBox.getSelectedItem().toString())) {
			JOptionPane.showConfirmDialog(null, "请填写SMTP服务器", "错误",
					JOptionPane.YES_NO_OPTION);
			return;
		} else if ("".equals(popComboBox.getSelectedItem().toString())) {
			JOptionPane.showConfirmDialog(null, "请填写POP3服务器", "错误",
					JOptionPane.YES_NO_OPTION);
			return;
		}
		user = new User();
		user.setUsername(usernameTextField.getText());
		user.setPassword(passwordTextField.getText());
		user.setSmtpServer(smtpComboBox.getSelectedItem().toString());
		user.setPopServer(popComboBox.getSelectedItem().toString());
		if (userlist.indexOf(user) == -1)
			userlist.add(user);
		File dir = new File("user/"+user.getUsername());
		if(!dir.exists()) dir.mkdirs();
		try {
			UserAction.save(userlist);
		} catch (IOException e) {
			e.printStackTrace();
		}
		this.dispose();
	}

	

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JScrollPane jScrollPane1;
	private java.awt.Label label1;
	private java.awt.Label label2;
	private java.awt.Label label3;
	private java.awt.Label label4;
	private javax.swing.JPasswordField passwordTextField;
	private javax.swing.JComboBox popComboBox;
	private javax.swing.JComboBox smtpComboBox;
	private javax.swing.JList userList;
	private javax.swing.JTextField usernameTextField;
	// End of variables declaration//GEN-END:variables

}