/*
 * WriteNewMail.java
 *
 * Created on __DATE__, __TIME__
 */

package dialog;

import java.io.File;
import java.io.IOException;
import java.util.Date;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import action.MailAction;
import data.Mail;
import data.User;

/**
 * 撰写新邮件
 * @author  spacelis
 */
public class WriteNewMail extends javax.swing.JDialog {
	User user = null;
	Mail mail = null;

	/** Creates new form WriteNewMail */
	public WriteNewMail(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
	}

	/**
	 * WriteNewMail构造方法
	 * @param user 当前用户
	 * @param mail 当前的邮件
	 */
	public WriteNewMail(User user, Mail mail) {
		this(new java.awt.Frame(), true);
		this.user = user;

		initComponents();
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent e) {
				dispose();
			}
		});
		if (mail != null) {
			this.mail = mail;
			toTextField.setText(mail.getTo());
			ccToTextField.setText(mail.getCc());
			BccTextField.setText(mail.getBcc());
			subjectTextField.setText(mail.getSubject());
			contentTextArea.setText(mail.getContent());
		}
		//发件人复选框
		fromComboBox.addItem(user.getUsername()
				+ "@"
				+ user.getSmtpServer().substring(
						user.getSmtpServer().indexOf(".") + 1));
		setLocation(340, 240);
		setVisible(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		toTextField = new javax.swing.JTextField();
		subjectTextField = new javax.swing.JTextField();
		ccToTextField = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		contentTextArea = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		fromComboBox = new javax.swing.JComboBox();
		jButton3 = new javax.swing.JButton();
		BccTextField = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		extraTextField = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jButton4 = new javax.swing.JButton();

		setTitle("\u5199\u65b0\u90ae\u4ef6");
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		jLabel1.setText("\u6536\u4ef6\u4eba");

		jLabel2.setText("\u4e3b\u9898");

		jLabel3.setText("\u6284\u9001");

		jLabel4.setText("\u6b63\u6587");

		contentTextArea.setColumns(20);
		contentTextArea.setRows(5);
		jScrollPane1.setViewportView(contentTextArea);

		jButton1.setText("\u53d1\u9001");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u53d6\u6d88");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel5.setText("\u53d1\u4ef6\u4eba");

		fromComboBox.setEditable(true);

		jButton3.setText("\u5b58\u8349\u7a3f");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jLabel6.setText("\u5bc6\u9001");

		extraTextField.setEditable(false);

		jLabel7.setText("\u9644\u4ef6");

		jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/icons/extra.png"))); // NOI18N
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.TRAILING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.TRAILING)
																						.add(
																								layout
																										.createSequentialGroup()
																										.addContainerGap()
																										.add(
																												jButton3)
																										.add(
																												53,
																												53,
																												53)
																										.add(
																												jButton1)
																										.add(
																												63,
																												63,
																												63))
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												29,
																												29,
																												29)
																										.add(
																												layout
																														.createParallelGroup(
																																org.jdesktop.layout.GroupLayout.TRAILING)
																														.add(
																																org.jdesktop.layout.GroupLayout.LEADING,
																																layout
																																		.createSequentialGroup()
																																		.add(
																																				jLabel3)
																																		.addPreferredGap(
																																				org.jdesktop.layout.LayoutStyle.RELATED)
																																		.add(
																																				ccToTextField,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																				242,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				org.jdesktop.layout.LayoutStyle.RELATED,
																																				81,
																																				Short.MAX_VALUE)
																																		.add(
																																				jLabel6,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																				37,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																																		.add(
																																				18,
																																				18,
																																				18)
																																		.add(
																																				BccTextField,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																				322,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																														.add(
																																org.jdesktop.layout.GroupLayout.LEADING,
																																layout
																																		.createSequentialGroup()
																																		.add(
																																				jLabel2)
																																		.addPreferredGap(
																																				org.jdesktop.layout.LayoutStyle.RELATED)
																																		.add(
																																				subjectTextField,
																																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																				700,
																																				Short.MAX_VALUE))
																														.add(
																																org.jdesktop.layout.GroupLayout.LEADING,
																																layout
																																		.createSequentialGroup()
																																		.add(
																																				jLabel1,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																				74,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				org.jdesktop.layout.LayoutStyle.RELATED)
																																		.add(
																																				toTextField,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																				242,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				org.jdesktop.layout.LayoutStyle.RELATED,
																																				76,
																																				Short.MAX_VALUE)
																																		.add(
																																				jLabel5)
																																		.add(
																																				26,
																																				26,
																																				26)
																																		.add(
																																				fromComboBox,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																				320,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																														.add(
																																layout
																																		.createParallelGroup(
																																				org.jdesktop.layout.GroupLayout.LEADING,
																																				false)
																																		.add(
																																				org.jdesktop.layout.GroupLayout.TRAILING,
																																				jScrollPane1,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																				777,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																																		.add(
																																				layout
																																						.createSequentialGroup()
																																						.add(
																																								jLabel7)
																																						.addPreferredGap(
																																								org.jdesktop.layout.LayoutStyle.RELATED)
																																						.add(
																																								extraTextField,
																																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																								383,
																																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																																						.addPreferredGap(
																																								org.jdesktop.layout.LayoutStyle.RELATED)
																																						.add(
																																								jButton4,
																																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																								31,
																																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																																						.addPreferredGap(
																																								org.jdesktop.layout.LayoutStyle.RELATED,
																																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																								Short.MAX_VALUE)
																																						.add(
																																								jButton2))))))
																		.add(
																				28,
																				28,
																				28))
														.add(
																org.jdesktop.layout.GroupLayout.LEADING,
																layout
																		.createSequentialGroup()
																		.add(
																				377,
																				377,
																				377)
																		.add(
																				jLabel4)))
										.addContainerGap(
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		layout.linkSize(new java.awt.Component[] { jLabel1, jLabel2, jLabel3,
				jLabel4 }, org.jdesktop.layout.GroupLayout.HORIZONTAL);

		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(22, 22, 22)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(
																jLabel1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																23,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																toTextField,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																fromComboBox,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel5))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel2)
														.add(
																subjectTextField,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel3)
														.add(
																ccToTextField,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																BccTextField,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																jLabel6,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																19,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jLabel4)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jScrollPane1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												359,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jButton3)
														.add(jButton1)
														.add(jButton2)
														.add(jLabel7)
														.add(
																extraTextField,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jButton4))
										.addContainerGap(16, Short.MAX_VALUE)));

		layout.linkSize(new java.awt.Component[] { jLabel1, jLabel2, jLabel3,
				jLabel4 }, org.jdesktop.layout.GroupLayout.VERTICAL);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * 添加附件
	 */
	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		//GEN-FIRST:event_AttachButtonActionPerformed
		JFileChooser fc = new JFileChooser();
		fc.setDialogTitle("请选择一个或者多个文件作为附件");
		//fc.setMultiSelectionEnabled(true);
		fc.setLocation(300, 200);
		fc.showOpenDialog(this);
		File extraFile = fc.getSelectedFile();
		extraTextField.setText(extraFile.getAbsolutePath());
	}

	/**
	 * 存草稿按钮响应
	 */
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {

		packMail();
		mail.setTime(new Date().getTime());
		try {
			MailAction.save(mail, "user/"+user.getUsername()+"/draftBox.dat");

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	/**
	 * 发送按钮响应
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		if (toTextField.getText().indexOf("@") == -1) {
			toTextField.setText(JOptionPane.showInputDialog(null, "请正确填写收件人邮箱",
					"错误提示", JOptionPane.OK_OPTION));
			return;
		}

		packMail();
		try {
			String msg = MailAction.send(user, mail);
			JOptionPane.showConfirmDialog(null, msg, "提示",
					JOptionPane.OK_OPTION);
			mail.setTime(new Date().getTime());
			MailAction.save(mail, "user/"+user.getUsername()+"/postBox.dat");
			dispose();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * 获取所填邮件信息
	 */
	public void packMail() {
		mail = new Mail();
		mail.setFrom(fromComboBox.getSelectedItem().toString());
		mail.setTo(toTextField.getText());
		mail.setCc(ccToTextField.getText());
		mail.setBcc(BccTextField.getText());
		mail.setSubject(subjectTextField.getText());
		mail.setContent(contentTextArea.getText());
		mail.setExtraFilename(extraTextField.getText());
	}

	/**
	 * 取消按钮响应
	 * @param evt
	 */
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		int confirm = JOptionPane.showConfirmDialog(null, "确定要放弃发送此邮件", "确认",
				JOptionPane.YES_NO_OPTION);
		if (confirm == JOptionPane.YES_OPTION) {
			dispose();
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField BccTextField;
	private javax.swing.JTextField ccToTextField;
	private javax.swing.JTextArea contentTextArea;
	private javax.swing.JTextField extraTextField;
	private javax.swing.JComboBox fromComboBox;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField subjectTextField;
	private javax.swing.JTextField toTextField;
	// End of variables declaration//GEN-END:variables

}